### ISSUE TITLE
Expand Hugging Face Documentation

### ISSUE THREAD

**Issue by mendonk** [LangStream/documentation#104]
Need more usage and context, specifically around e5-xxx-v2 embeddings.

**Comment by eolivelli** [comment]
In this patch we added a sample application for text embeddings, computed locally
https://github.com/LangStream/langstream/pull/584

**Comment by eolivelli** [comment]
Here it is
https://github.com/LangStream/langstream/tree/main/examples/applications/compute-hugging-face-embeddings

It works only on 0.2.1+ (not up to 0.2.0, because we needed some fixes, committed with https://github.com/LangStream/langstream/pull/584)
