### ISSUE TITLE
Add section on how templating works

### ISSUE THREAD

**Issue by cdbartholomew** [LangStream/documentation#59]
I am a bit confused about how templating works in LangStream. See https://github.com/LangStream/langstream/issues/425 as an example of my confusion.

I think we need to add a section to the docs that describes templating in general and how it is used in LangStream. I couldn't find anything like this while searching and I think this would be very useful. It will also serve as good source text for the chatbot for when anyone has any templating questions.

**Comment by eolivelli** [comment]
done
