### ISSUE TITLE
Web crawler can accept multiple URLs

### ISSUE THREAD

**Issue by cdbartholomew** [LangStream/documentation#74]
Because the properties are plural for `seed-urls` and `allowed-domains` I assumed that I could specify multiple for each. However, the documentation didn't mention this. 

By having ChatGPT analyze the code, I confirmed that both can be specified like this:
```
{
  "seed-urls": ["http://example1.com", "http://example2.com"]
}
```

We need to add this detail to the docs.

**Comment by cdbartholomew** [comment]
I have confirmed that this works. Note that the YAML can also be specified in this format:
```
seed-urls:
  - "http://example1.com"
  - "http://example2.com"
```
This is a common alternate way to specify lists in YAML.

**Comment by mendonk** [comment]
https://docs.langstream.ai/pipeline-agents/input-and-output/webcrawler-source#multiple-urls-in-pipeline
